// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqvwbmyegcesibksobzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xdndibXllZ2Nlc2lia3NvYnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjIwNzUsImV4cCI6MjA3Mzc5ODA3NX0.8gx63DBImw26bjMflN2JemiaWHPGGi16W4h9W-K_17Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'herbaltrace-web'
    }
  }
});

// Convenient export for Storage service
export const storage = supabase.storage;